### ISSUE TITLE
how you compine svg paths for Colombia map

### ISSUE THREAD

**Issue by salahatwa** [MiguelRodriguezR/CoronavirusColombia#1]
Thanks for providing great simple code , 
for your gentle support to provide us , how you collect paths in department.ts file for Colombia ,
how can we do that for another country like egypt map , 
thanks ,

**Comment by MiguelRodriguezR** [comment]
Hello @salahatwa, answering your question I got the map of Colombia from [simplemaps.com](https://simplemaps.com/resources/svg-co), then I manualy added to each path the department name acording to the names provided by [Datos Abiertos dataset](https://www.datos.gov.co/Salud-y-Protecci-n-Social/Casos-positivos-de-COVID-19-en-Colombia/gt2j-8ykr/data)

**Comment by salahatwa** [comment]
Thanks for your great help

**Comment by MiguelRodriguezR** [comment]
> Thanks for your great help

you're wellcome man.
